AddressHistoryWebApp/Models/ErrorViewModel.cs
using System;

namespace AddressHistoryWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AddressHistoryWebApp/Controllers/AddressController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using AddressHistoryDAL;
using AddressHistoryDAL.Models;
using AddressHistoryDAL.Repos;

namespace AddressHistoryWebApp.Controllers
{
    public class AddressController : Controller
    {
        private readonly IDataRepo _repo;

        public AddressController(IDataRepo repo)
        {
            _repo = repo;
        }

        // GET: Address
        public IActionResult Index()
        {
            return View();
        }

        // GET: Address
        public IActionResult All()
        {
            return View("List", _repo.GetAddresses());
        }

        // POST: Address/ListDate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ListDate(string date, bool single)
        {
            try
            {
                if (date != null && !date.Equals("mm/dd/yyyy"))
                {
                    DateTime _startdate = DateTime.Parse(date);

                    if (single)
                    {
                        return View("Single", _repo.GetAddress(_startdate));
                    }

                    return View("List", _repo.GetAddresses(_startdate));
                }

                throw new Exception("Invalid date input.");
            }
            catch (Exception ex)
            {
                InputOutput logger = InputOutput.GetInstance();

                ex.Data.Add("Class:", "AddressController");
                ex.Data.Add("Method:", "ListCalcDate(string date, bool single)");
                ex.Data.Add("years:", $"\"{date}\"");

                logger.WriteLogFile(ex);
            }

            return BadRequest();
        }

        // POST: Address/ListCalcDate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ListCalcDate(string years, bool single)
        {
            try
            {
                bool _success = int.TryParse(years, out int _num);
                if (_success)
                {
                    string _date = DateTime.Now.AddYears(-_num).ToString("MM/dd/yyyy");

                    DateTime _startdate = DateTime.Parse(_date);

                    if (single)
                    {
                        return View("Single", _repo.GetAddress(_startdate));
                    }

                    return View("List", _repo.GetAddresses(_startdate));
                }
                else
                {
                    throw new Exception("Cannot convert string years to integer.");
                }
            }
            catch (Exception ex)
            {
                InputOutput logger = InputOutput.GetInstance();

                ex.Data.Add("Class:", "AddressController");
                ex.Data.Add("Method:", "ListCalcDate(string years, bool single)");
                ex.Data.Add("years:", $"\"{years}\"");

                logger.WriteLogFile(ex);
            }

            return BadRequest();
        }

        // GET: Address/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Address/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("StartDate,EndDate,Address1,Address2,City,State,Zip5,Zip4")] Address address)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _repo.InsertAddress(address);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, $@"Unable to add addess: {ex.Message}");
                    return View(address);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(address);
        }

        // GET: Address/Edit/5
        public IActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            DateTime _startDate = DateTime.Parse(id);

            Address _address = _repo.GetAddress(_startDate);

            if (_address == null)
            {
                return NotFound();
            }
            return View(_address);
        }

        // POST: Address/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DateTime id, [Bind("StartDate,EndDate,Address1,Address2,City,State,Zip5,Zip4")] Address address)
        {
            if (id != address.StartDate)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _repo.UpdateAddress(address);
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    ModelState.AddModelError(string.Empty, $@"Unable to update address. Another user has updated it. {ex.Message}");
                    return View(address);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, $@"Unable to update the address. {ex.Message}");
                    return View(address);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(address);
        }

        // GET: Address/Delete/5
        public IActionResult Delete()
        {
            Address _address = _repo.GetLastAddress();

            if (_address == null)
            {
                return NotFound();
            }

            return View(_address);
        }

        // POST: Inventory/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind("Id,Timestamp")] Address address)
        {
            try
            {
                _repo.DeleteAddress();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to delete record. Another user updated the record. {ex.Message}");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create record: {ex.Message}");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

AddressHistoryWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AddressHistoryWebApp.Models;

namespace AddressHistoryWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AddressHistoryWebApp/Views/Address/Create.cshtml
@model AddressHistoryDAL.Models.Address

@{
    ViewData["Title"] = "Add An Address";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <h4>Address</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Address1" class="control-label"></label>
                    <input asp-for="Address1" class="form-control" />
                    <span asp-validation-for="Address1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address2" class="control-label"></label>
                    <input asp-for="Address2" class="form-control" />
                    <span asp-validation-for="Address2" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="State" class="control-label"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Zip5" class="control-label"></label>
                    <input asp-for="Zip5" class="form-control" />
                    <span asp-validation-for="Zip5" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Zip4" class="control-label"></label>
                    <input asp-for="Zip4" class="form-control" />
                    <span asp-validation-for="Zip4" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

AddressHistoryWebApp/Views/Address/Delete.cshtml
@model AddressHistoryDAL.Models.Address
@using Microsoft.AspNetCore.Html

@{
    ViewData["Title"] = "Delete An Address";
}

@functions {

private IHtmlContent DisplayEmptyCell(string cell)
{
    if (string.IsNullOrEmpty(cell))
    {
        return Html.Raw("&nbsp;");
    }

    return Html.Raw(cell);
}
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EndDate)
            </dt>
            <dd class="col-sm-10">
                &nbsp;
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address1)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address1)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address2)
            </dt>
            <dd class="col-sm-10">
                @DisplayEmptyCell(Model.Address2)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.City)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.State)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.State)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Zip5)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Zip5)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Zip4)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Zip4)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="StartDate" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</body>
</html>

AddressHistoryWebApp/Views/Address/Edit.cshtml
@model AddressHistoryDAL.Models.Address

@{
    ViewData["Title"] = "Edit An Address";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

    <h4>Address</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="StartDate" />
                <input type="hidden" asp-for="EndDate" />
                <div class="form-group">
                    <label asp-for="Address1" class="control-label"></label>
                    <input asp-for="Address1" class="form-control" />
                    <span asp-validation-for="Address1" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address2" class="control-label"></label>
                    <input asp-for="Address2" class="form-control" />
                    <span asp-validation-for="Address2" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="State" class="control-label"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Zip5" class="control-label"></label>
                    <input asp-for="Zip5" class="form-control" />
                    <span asp-validation-for="Zip5" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Zip4" class="control-label"></label>
                    <input asp-for="Zip4" class="form-control" />
                    <span asp-validation-for="Zip4" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

AddressHistoryWebApp/Views/Address/Index.cshtml
@model IEnumerable<AddressHistoryDAL.Models.Address>

@{
    ViewData["Title"] = "Addresses Home Page";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body id="addresses">
    <div class="my-md-5">
        <p>
            <a asp-controller="Address" asp-action="All" class="btn btn-primary">List / Edit Addresses</a>
            <a asp-controller="Address" asp-action="Create" class="btn btn-primary">Add Address</a>
            <a asp-controller="Address" asp-action="Delete" class="btn btn-primary">Delete Address</a>

        </p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <form asp-controller="Address" asp-action="ListDate">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <fieldset class="form-group">
                        <legend>Specific date</legend>
                        <div class="form-group form-inline">
                            <label for="date" class="control-label">Date</label>
                            <input type="text" id="date" name="date" placeholder="mm/dd/yyyy" class="form-control col-sm-5 offset-sm-1" />
                        </div>
                        <div class="form-group form-check">
                            <label><input type="radio" name="single" value="true" class="form-check-input" />Single Address</label><br />
                            <label><input type="radio" name="single" value="false" class="form-check-input" checked />List of Addresses</label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Submit" class="btn btn-outline-primary btn-sm" />
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="col">
                <form asp-controller="Address" asp-action="ListCalcDate">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <fieldset class="form-group">
                        <legend>Calculated date</legend>
                        <div class="form-group form-inline">
                            <label for="years" class="control-label">Number of years to subtract</label>
                            <input type="text" id="years" name="years" value="" class="form-control col-sm-2 offset-sm-1" />
                        </div>
                        <div class="form-group form-check">
                            <label><input type="radio" name="single" value="true" class="form-check-input" />Single Address</label><br />
                            <label><input type="radio" name="single" value="false" class="form-check-input" checked />List of Addresses</label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Submit" class="btn btn-outline-primary btn-sm" />
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

AddressHistoryWebApp/Views/Address/List.cshtml
@model IEnumerable<AddressHistoryDAL.Models.Address>

@{
    ViewData["Title"] = "Address List";
}

@functions {

private string DisplayZip(string zip5, string zip4)
{
    if (string.IsNullOrEmpty(zip4))
    {
        return zip5;
    }

    return zip5 + "-" + zip4;
}

private string DisplayEndDate(string date)
{
    if (date.Equals("12/31/9999"))
    {
        return string.Empty;
    }

    return date;
}
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.StartDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address2)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.State)
                </th>
                <th>
                    Zip Code
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @DisplayEndDate(item.EndDate.ToString("MM/dd/yyyy"))
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.State)
                    </td>
                    <td>
                        @DisplayZip(item.Zip5, item.Zip4)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.StartDate.ToString("yyyy-MM-dd")">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p>
        <a asp-action="Index" class="btn btn-primary">Back</a>
    </p>
</body>
</html>

AddressHistoryWebApp/Views/Address/Single.cshtml
@model AddressHistoryDAL.Models.Address

@{
    ViewData["Title"] = "Single Address";
}

@functions {

private string DisplayZip(string zip5, string zip4)
{
    if (string.IsNullOrEmpty(zip4))
    {
        return zip5;
    }

    return zip5 + "-" + zip4;
}

private string DisplayEndDate(string date)
{
    if (date.Equals("12/31/9999"))
    {
        return string.Empty;
    }

    return date;
}
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.StartDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address2)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.State)
                </th>
                <th>
                    Zip Code
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.StartDate)
                </td>
                <td>
                    @DisplayEndDate(Model.EndDate.ToString("MM/dd/yyyy"))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.Address1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.Address2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.State)
                </td>
                <td>
                    @DisplayZip(Model.Zip5, Model.Zip4)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@Model.StartDate.ToString("yyyy-MM-dd")">Edit</a>
                </td>
            </tr>
        </tbody>
    </table>
    <p>
        <a asp-action="Index" class="btn btn-primary">Back</a>
    </p>
</body>
</html>

AddressHistoryWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>
<div class="w-75">
    <p>
        Welcome to the AddressHistory application!
    </p>
    <p>
        The purpose of this application is to allow you to store your home addresses and look them up based on a specific date. You can search for a particular address or have a list of addresses displayed for your reference.
    </p>
    <p class="clearfix">
        <img class="float-md-left mr-md-3" src="~/images/2118.jpg" alt="hand-completing-application-form" />
        Why an application to store and look up addresses? Consider forms! You may be filling out a job or credit application or some other paperwork. You are requested to list your addresses going back some number of years, usually three, five, or seven years. With the AddressHistory application, you enter the required date or the number of years to go back, and the list you need is displayed. All you have to do is write it on the form!
    </p>
    <p class="clearfix">
        <img class="float-md-right ml-md-3" src="~/images/18589.jpg" alt="puzzled-phone-user-getting-concerning-news" />
        You may also use the application when you are reminiscing or talking with family or friends. You may consider where you were living when an event occurred. Whatever the reason, you can look up the information when not sure of your recollection.
    </p>
    <p class="text-md-center fixed-bottom">
        <small>
            <a href="https://www.freepik.com/free-photos-vectors/business">Business photo created by katemangostar - www.freepik.com</a> |
            <a href="https://www.freepik.com/free-photos-vectors/background">Background photo created by katemangostar - www.freepik.com</a>
        </small>
    </p>
</div>

AddressHistoryWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AddressHistory - @ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AddressHistory</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Address" asp-action="Index">Addresses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white">
        <div class="container">
            &copy; <script>document.write(new Date().getFullYear())</script> - AddressHistory
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>